### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by XionioXMaster** [Aizistral-Studios/Enigmatic-Legacy#207]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.5
 * Curios API: curios-forge-1.16.5-4.0.5.3.jar
 * Patchouli: Patchouli-1.16.4-53.2.jar
 * Forge: 36.2.6

#### Description of a Bug:
idk
#### How to Reproduce:
1.idk

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://paste.loliidc.cn/?2ec966dcbbe49993#AXndM1mydgGqkdQmKvsUiYDKQg8wznQXxttBZLq58nQE

**Comment by Aizistral** [comment]
Blast. Man, I can't help you if do not at least provide your logs. It's not even funny any longer.

**Comment by XionioXMaster** [comment]
> Blast. Man, I can't help you if do not at least provide your logs. It's not even funny any longer.

It's funny, for some reason the magazine did not go, although I attached it XD

**Comment by Aizistral** [comment]
I'll look into this.

**Comment by Aizistral** [comment]
Really
![image](https://user-images.githubusercontent.com/47505981/140997403-4e12c7ff-08e5-4b41-b465-2b1b3bddaeba.png)
