### ISSUE TITLE
Ender chest icon that is always out of position

### ISSUE THREAD

**Issue by XionioXMaster** [Aizistral-Studios/Enigmatic-Legacy#236]
If you play actively on the server with this mod for a long time, the icon of the ender chest in the player's inventory starts to reset across the entire inventory! Often occurs when opening a recipe book

![image](https://user-images.githubusercontent.com/86433158/149221422-f7f41a9e-7db6-40ab-9112-9ee3e5cc5b8b.png)

I'm use Quark mod and enigmatic 1.16.5 2.11.9

**Comment by Aizistral** [comment]
Please use proper bug report form.
