### ISSUE TITLE
Charged jump

### ISSUE THREAD

**Issue by Tillllt** [Aizistral-Studios/Enigmatic-Legacy#35]
In vanilla minecraft there are Jump Boost status effect, but it's not convenient to use in many reasons. Most because you jump higher than you used to and your crit DPS is lower.
Is it possible to add in Your mod replacement for that status effect with charged jump? Like it works on horses or in Smart Moving mod.

**Comment by Tillllt** [comment]
Or maybe add new Charged Jump status effect for beacons and potions?

**Comment by Extegral** [comment]
This is incredibly subtle improvement, in my mind. It's definitely possible to implement in it's own status effect/item/ability/whatever, but I don't have certainty it will be that useful.
I may consider implementing, but won't be putting this among current delelopment priorities.

**Comment by Tillllt** [comment]
Of course! I just offered.

**Comment by Nechronom** [comment]
Maybe this would be a good sort of idea to work into the Elytra Flight Enhancing Item? Allowing for someone with flight to take off, or someone without it to simply get really good hops?

**Comment by Aizistral** [comment]
> Maybe this would be a good sort of idea to work into the Elytra Flight Enhancing Item? Allowing for someone with flight to take off, or someone without it to simply get really good hops?

Nah. Majestic Elytra will be pretty easy to take off with, conventional can be used with Angel's Blessing to achieve such effect.
